//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int EFkey { get; set; }
        public string SKU { get; set; }
        public string Name { get; set; }
        public string FormSize { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
