//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCServiceClient.PlantWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlantItem", Namespace="http://schemas.datacontract.org/2004/07/DTObjects")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MVCServiceClient.PlantWCF.PlantDetail))]
    public partial class PlantItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlantDetail", Namespace="http://schemas.datacontract.org/2004/07/DTObjects")]
    [System.SerializableAttribute()]
    public partial class PlantDetail : MVCServiceClient.PlantWCF.PlantItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormSize {
            get {
                return this.FormSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormSizeField, value) != true)) {
                    this.FormSizeField = value;
                    this.RaisePropertyChanged("FormSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlantWCF.IPlants")]
    public interface IPlants {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlants/GetAll", ReplyAction="http://tempuri.org/IPlants/GetAllResponse")]
        MVCServiceClient.PlantWCF.PlantItem[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlants/GetAll", ReplyAction="http://tempuri.org/IPlants/GetAllResponse")]
        System.Threading.Tasks.Task<MVCServiceClient.PlantWCF.PlantItem[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlants/GetBySKU", ReplyAction="http://tempuri.org/IPlants/GetBySKUResponse")]
        MVCServiceClient.PlantWCF.PlantDetail GetBySKU(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlants/GetBySKU", ReplyAction="http://tempuri.org/IPlants/GetBySKUResponse")]
        System.Threading.Tasks.Task<MVCServiceClient.PlantWCF.PlantDetail> GetBySKUAsync(string sku);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlantsChannel : MVCServiceClient.PlantWCF.IPlants, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlantsClient : System.ServiceModel.ClientBase<MVCServiceClient.PlantWCF.IPlants>, MVCServiceClient.PlantWCF.IPlants {
        
        public PlantsClient() {
        }
        
        public PlantsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlantsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlantsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCServiceClient.PlantWCF.PlantItem[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<MVCServiceClient.PlantWCF.PlantItem[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public MVCServiceClient.PlantWCF.PlantDetail GetBySKU(string sku) {
            return base.Channel.GetBySKU(sku);
        }
        
        public System.Threading.Tasks.Task<MVCServiceClient.PlantWCF.PlantDetail> GetBySKUAsync(string sku) {
            return base.Channel.GetBySKUAsync(sku);
        }
    }
}
